<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

////////new
use App\Models\Product\ProductOption;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
class TypeOptions extends Seeder
{
    /**            
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("SET foreign_key_checks=0");
        DB::table('product_options')->truncate();
        DB::statement("SET foreign_key_checks=1");
        ////////////////////////////////
        $now = Carbon::now();
        $options=[
            ['product_spec_id' => '1',
                'name' => 'Hp',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '1',
                'name' => 'Dell',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '1',
                'name' => 'Asus',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '1',
                'name' => 'Apple',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ////////////////////////////////////////////////////////////
            ['product_spec_id' => '2',
                'name' => 'corei5',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '2',
                'name' => 'corei3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '2',
                'name' => 'corei7',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ///////////////////////////////////////////////////////////////////
            ['product_spec_id' => '3',
                'name' => '8G',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['type_product_spec_idspec_id' => '3',
                'name' => '6G',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '3',
                'name' => '16G',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '3',
                'name' => '32G',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '3',
                'name' => '64G',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ///////////////////////////////////////////
            ['product_spec_id' => '4',
                'name' => 'Red',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '4',
                'name' => 'Black',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '4',
                'name' => 'selver',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ///////////////////////////////////////////////////////
            ['product_spec_id' => '5',
                'name' => '1000$',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '5',
                'name' => '2000$',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '5',
                'name' => '2500$',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            /////////////////////////////////////////////////////////////
            ['product_spec_id' => '6',
                'name' => 'samsung',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '6',
                'name' => 'Hawawi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '6',
                'name' => 'Iphone',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ////////////////////////////////////////////////////////////////////
            //// for cpu 
            ['product_spec_id' => '7',
                'name' => 'multi-core processors',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '7',
                'name' => ', quad-core',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '7',
                'name' => 'octa-core',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            /////////////////////////////////////////////////////
            ['product_spec_id' => '8',
                'name' => '8G',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '8',
                'name' => '7G',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '8',
                'name' => '6G',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '8',
                'name' => '16G',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //////////////////////////////////////////////////////////////////
            ['product_spec_id' => '9',
                'name' => '256G',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '9',
                'name' => '512G',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '9',
                'name' => '128G',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //////////////////////////////////////////////////////////////////////
            ['product_spec_id' => '10',
                'name' => 'Green',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '10',
                'name' => 'Red',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '10',
                'name' => 'Black',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ////////////////////////////////////////////////////////////////////////////
            ['product_spec_id' => '11',
                'name' => '300$',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '11',
                'name' => '200$',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '11',
                'name' => '500$',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            /////////////////////////////////////////////////////////////////////////////
            ['product_spec_id' => '12',
                'name' => 'Digital',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '12',
                'name' => 'Samsung',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '12',
                'name' => 'Hawawi',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //////////////////////////////////////////////////////////////////////////////
            ['product_spec_id' => '13',
                'name' => 'Black',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '13',
                'name' => 'Red',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '13',
                'name' => 'Selver',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ////////////////////////////////////////////////////////////////////////
            ['product_spec_id' => '14',
                'name' => '100$',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '14',
                'name' => '200$',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ['product_spec_id' => '14',
                'name' => '350$',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            ///  the end of camera Specfication 
            ////////////////////////////////////////////////////////////////////////////////////
            
        ];
        
        foreach ($options as $option)
        DB::table('product_options')->insert($option);
    }
}
